id: P000018
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །འདིར་རང་གཞན་ལ་བསླབ་བྱ་གྲོས་འདེབས་ཀྱི་སྐོར་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་ལྷག་བསམ་རབ་དཀར་པདྨའི་འཕྲེང་བའོ།
    །
  authors:
  - མཛད་པ་པོ། མཁས་གྲུབ་ཆེན་པོ་རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  layers:
  - book_title
  - author
  - chapter_title
  - quotation
  - yigchung
  id: TSD-TSE-08
web_metadata:
  title:
    en: A Lotus Garland of Pure Intention:A Collection of Various Spiritual Advice
    bo: འདིར་རང་གཞན་ལ་བསླབ་བྱ་གྲོས་འདེབས་ཀྱི་སྐོར་རྣམས་ཕྱོགས་གཅིག་ཏུ་བསྡེབས་པ་ལྷག་བསམ་རབ་དཀར་པདྨའི་འཕྲེང་བའོ།
  collection:
    en: Tsele Natsok Rangdrol Series–  Book 8
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།–  དེབ། ༨
  author:
    en: Tsele Natsok Rangdrol
    bo: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ།
  pusblisher:
    en: Tsadra Foundation Publishing
    bo: ཙཱ་འདྲ་ཐེབས་རྩ་ཚོགས་པ།
  sku: TSD-TSE-08
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: TSD-TSE-08.epub
  description:
    en: ''
    bo: ''
